#!/usr/bin/env python3
// script that adds a new attribute to a document in the collection school:
//update ame="Holberton school"- address  with the value “972 Mission street
db.school.find ({name : "Holberton school"}{ $set :address :  “972 Mission street”})

