#!/usr/bin/env python3
// script that adds a new attribute to a document in the collection school:
//update ame="Holberton school"- address  with the value “972 Mission street
db.school.update ({name : "Holberton school"}{ address :  “972 Mission street”});
