CREATE TABLE users(
ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL
name VARCHAR(255)
);
ALTER TABLE users
ADD COLUMN IF NOT EXISTS id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL;
ADD COLUMN IF NOT EXISTS email VARCHAR(255) UNIQUE NOT NULL;
ADD COLUMN IF NOT EXISTS name VARCHAR(255);
